name: comment_repository
version: 1.0.0
publish_to: none
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^1.0.1
  cloud_firestore: ^1.0.1
  equatable: ^1.2.5
  post_repository:
    path: ../post_repository