name: authentication_repository
description: Dart packages which manages the authentication domain.
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^1.2.5
  firebase_auth: ^1.0.1
  firebase_core: ^1.0.1
  cloud_firestore: ^1.0.1
  google_sign_in: ^5.0.0
  flutter_facebook_login: ^3.0.0
  meta: ^1.1.8

