name: file_picker_repository
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^3.0.0
  image_picker: ^0.7.2+1
  image_cropper: ^1.3.1
  equatable: ^1.2.5